services:
  whisperx:
    build: .
    container_name: whisperx_audio_pipeline
    env_file:
      - .env
    environment:
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    volumes:
      - /volume1/audio_pipeline:/pipeline
      - /volume1/audio_pipeline/processing/hf_cache:/root/.cache/huggingface
    working_dir: /pipeline

  whisperx_worker:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /volume1/audio_pipeline:/pipeline
      - /volume1/audio_pipeline/processing/hf_cache:/root/.cache/huggingface
    working_dir: /pipeline
    command: >
      bash -lc "/pipeline/scripts/watch_incoming.sh"
